version: '3'

services:
  tad:
    image: postgres:9.6
    container_name: 'postgres'
    environment:
      - POSTGRES_DB=gostack_desafio06
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - TZ=GMT
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432
